### ISSUE TITLE
RuntimeError: indices should be on cpu

### ISSUE THREAD

**Issue by Bengt** [facebookresearch/ParlAI#5013] opened 2023-04-18 12:07 UTC
When I run the tutorial on Google Colab, I get this error:

```
RuntimeError                              Traceback (most recent call last)
[<ipython-input-3-4afa600fbda9>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 # call it with particular args
----> 5 Interactive.main(
      6     # the model_file is a filename path pointing to a particular model dump.
      7     # Model files that begin with "zoo:" are special files distributed by the ParlAI team.

10 frames
[/usr/local/lib/python3.9/dist-packages/parlai/core/torch_generator_agent.py](https://localhost:8080/#) in advance(self, logprobs, step)
   1597         self.partial_hyps = torch.cat(
   1598             (
-> 1599                 self.partial_hyps[path_selection.hypothesis_ids.long()],
   1600                 path_selection.token_ids.view(path_selection.token_ids.shape[0], -1).to(
   1601                     hyp_device

RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

**Comment by Bengt** [comment] 2023-04-18 12:09
This happens in the "Chatting with a model" cell.

**Comment by Bengt** [comment] 2023-04-18 12:10
I used "run all cells" with a GPU accelerator.

**Comment by Bengt** [comment] 2023-04-18 12:13
When I select "None" as accelerator for my Colab instance, this works fine.

**Comment by Bengt** [comment] 2023-04-18 12:40
This seems to be a duplicate of #4976

**Comment by klshuster** [comment] 2023-04-19 20:14
Yes, as you've found it is indeed a duplicate of #4976, closing in favor of that issue

**Closed by klshuster** 2023-04-19 20:14 UTC
