### ISSUE TITLE
OSError: Error 22 while following tutorial docs

### ISSUE THREAD

**Issue by superchargez** [facebookresearch/ParlAI#3907] opened 2021-08-05 10:40 UTC
**Bug description**
Can't run babi_memn to ask it questions. training and evaluation ran smoothly without errors.

**Reproduction steps**
Run the following command from tutorial
parlai interactive --model-file /tmp/babi_memnn --eval-candidates vocab

**Logs**
03:27:05 | epoch done
Traceback (most recent call last):
  File "C:\Users\PTCL\anaconda3\envs\bot\Scripts\parlai-script.py", line 33, in <module>
    sys.exit(load_entry_point('parlai', 'console_scripts', 'parlai')())
  File "d:\jawad\python\gpt_chat\parlai\parlai\__main__.py", line 14, in main
    superscript_main()
  File "d:\jawad\python\gpt_chat\parlai\parlai\core\script.py", line 325, in superscript_main
    return SCRIPT_REGISTRY[cmd].klass._run_from_parser_and_opt(opt, parser)
  File "d:\jawad\python\gpt_chat\parlai\parlai\core\script.py", line 108, in _run_from_parser_and_opt
    return script.run()
  File "d:\jawad\python\gpt_chat\parlai\parlai\scripts\interactive.py", line 118, in run
    return interactive(self.opt)
  File "d:\jawad\python\gpt_chat\parlai\parlai\scripts\interactive.py", line 84, in interactive
    agent = create_agent(opt, requireModelExists=True)
  File "d:\jawad\python\gpt_chat\parlai\parlai\core\agents.py", line 468, in create_agent
    model = create_agent_from_opt_file(opt)
  File "d:\jawad\python\gpt_chat\parlai\parlai\core\agents.py", line 421, in create_agent_from_opt_file
    return model_class(opt_from_file)
  File "d:\jawad\python\gpt_chat\parlai\parlai\agents\memnn\memnn.py", line 79, in __init__
    super().__init__(opt, shared)
  File "d:\jawad\python\gpt_chat\parlai\parlai\core\torch_ranker_agent.py", line 190, in __init__
    super().__init__(opt, shared)
  File "d:\jawad\python\gpt_chat\parlai\parlai\core\torch_agent.py", line 840, in __init__
    self.set_interactive_mode(opt.get('interactive_mode', False), shared)
  File "d:\jawad\python\gpt_chat\parlai\parlai\core\torch_ranker_agent.py", line 310, in set_interactive_mode
    path = self.get_task_candidates_path()
  File "d:\jawad\python\gpt_chat\parlai\parlai\core\torch_ranker_agent.py", line 334, in get_task_candidates_path
    build_cands(opt)
  File "d:\jawad\python\gpt_chat\parlai\parlai\scripts\build_candidates.py", line 90, in build_cands
    fw = open(outfile, 'w')
OSError: [Errno 22] Invalid argument: '/tmp/babi_memnn.cands-babi:task10k:1.cands'```

**Additional context**
This is page one on tutorial, under section (Quick Start)

**Comment by klshuster** [comment] 2021-08-05 16:58
closing, as this is a duplicate of #3828; please see information there

**Closed by klshuster** 2021-08-05 16:58 UTC
