### ISSUE TITLE
Update tasks in task_list.py

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/ParlAI#108] opened 2017-05-29 04:18 UTC
The list of tasks in [task_list.py](https://github.com/facebookresearch/ParlAI/blob/master/parlai/tasks/task_list.py) is outdated and does not include tasks like VQA and VisDial.

**Comment by jaseweston** [comment] 2017-05-31 03:07
Duplicate of issue https://github.com/facebookresearch/ParlAI/issues/73.
However -- we will do this v. soon!

**Closed** 2017-05-31 03:07 UTC
