### ISSUE TITLE
Visit all examples in dataset using API

### ISSUE THREAD

**Issue by aleSuglia** [facebookresearch/ParlAI#635] opened 2018-03-13 17:54 UTC
Hi everyone,

I'm trying to write a script in order to extract some information for each datasets in ParlAI. I was trying to use the world API in this way:
```
agent = RepeatLabelAgent(opt)
world = create_task(opt, agent)
dialogues = []

    with world:
        for _ in range(world.num_episodes()):
            dialogue = []
            while not world.episode_done():
                world.parley()
                acts = world.get_acts()
                dialogue.append((acts[0]["text"], acts[1]["text"]))
            
            if world.epoch_done():
                break
```
At the moment I'm only able to iterate over two examples for each dataset. This sounds a bit weird to me because using the two inner loops I should be able to iterate for each episode and extract each turn from it. Also, at least in dialogue-based datasets I would expect that each episode is considered a dialogue but it seems not the case and I think that it is counterintuitive.

Am I doing something wrong? To me seems the correct way to proceed but apparently the operation that I'm doing are not supported.

Thanks!

**Comment by alexholdenmiller** [comment] 2018-03-13 20:10
Hi @aleSuglia, the issue is with the `while not world.episode_done()` statement. It does not get reset until you call parlai again, so it gets stuck really fast in this case. Here's my version which I think does what you're looking for:

```
from parlai.agents.repeat_label.repeat_label import RepeatLabelAgent
from parlai.core.agents import create_agent
from parlai.core.worlds import create_task
from parlai.core.params import ParlaiParser

parser = ParlaiParser()
opt = parser.parse_args()

agent = RepeatLabelAgent(opt)
world = create_task(opt, agent)
dialogues = []
dialogue = []

with world:
    while not world.epoch_done():
        world.parley()
        acts = world.get_acts()
        dialogue.append((acts[0]["text"], acts[1]["text"]))
        if world.episode_done():
            dialogues.append(dialogue)
            dialogue = []

print(dialogues)
```

**Comment by alexholdenmiller** [comment] 2018-03-13 22:37
(closing for now but feel free to reopen)

**Closed by alexholdenmiller** 2018-03-13 22:37 UTC
Labels: question
