### ISSUE TITLE
How to reproduce the best performance of KV Profile Memory Network

### ISSUE THREAD

**Issue by wtma** [facebookresearch/ParlAI#2225] opened 2019-11-26 01:18 UTC
Hello, I try to reproduce the model KV Profile Memory which has best performance in your paper 'Personalizing Dialogue Agents: I have a dog, do you have pets too'. 
For the task 'No Persona', I train the model by the script just like kvmemnn_train.sh:
python examples/train_model.py -m projects.personachat.kvmemnn.kvmemnn:KvmemnnAgent -t personachat:none -ltim 60 -vme 10000 -vtim 900 --hops 1 --lins 0 -vp -1 -vmt accuracy -ttim 28800 -shareEmb True -bs 1 -lr 0.1 -esz 500 --margin 0.1 --tfidf False --numthreads 10 -mf "./model/baseline1/persona_none.model"
**The hits@1 in validation: 31.3, test: 31.8, while the score in the paper is 34.9.**

 For the task 'Original Persona', I train the model by script kvmemnn_train.sh:
python examples/train_model.py -m projects.personachat.kvmemnn.kvmemnn:KvmemnnAgent -t personachat -ltim 60 -vme 10000 -vtim 900 --hops 1 --lins 0 -vp -1 -vmt accuracy -ttim 28800 -shareEmb True -bs 1 -lr 0.1 -esz 500 --margin 0.1 --tfidf False --numthreads 10 -mf "./model/self_ori_baseline/model_self_original"
**The hits@1 in validation: 47.9, test: 48.1, and the score in the paper is 51.1.**

At last, I try to reproduce the pre-train model by run the command:
' python projects/personachat/scripts/kvmemnn_eval.py'.
And I get the error:
Traceback (most recent call last):
  File "projects/personachat/scripts/kvmemnn_eval.py", line 35, in <module>
    eval_model(parser)
  File "/data/disk3/wtma/pr_emb/ParlAI/parlai/scripts/eval_model.py", line 108, in eval_model
    agent = create_agent(opt, requireModelExists=True)
  File "/data/disk3/wtma/pr_emb/ParlAI/parlai/core/agents.py", line 659, in create_agent
    if opt.get('datapath', None) is None:
AttributeError: 'ParlaiParser' object has no attribute 'get'

Could you please help me reproduce the performance of the model KV Profile Memory? That is very important for me to fellow the paper. Thank you so much!

**Comment by stephenroller** [comment] 2019-11-26 04:45
So the alreasypretrained model exists, and should be able to reproduce the numbers without issue. We in fact have an integration test that verifies its performance (https://github.com/facebookresearch/ParlAI/blob/930f0deea5a4264aefce2a809ca0e47b6e24951e/tests/nightly/gpu/test_convai2.py#L51), but there are some caveatsof changes between the 2017 and 2018 iterations.

The stack trace you’re seeing looks like a minor bug that can be fixed easily. Instead of passing the parser directly, we need to update it to pass the result of parser.parse_args(). Someone will patch it soon, or you may feel free to make a PR.

**Comment by wtma** [comment] 2019-11-26 06:38
I'm sorry for not expressing it clearly!
There is no doubt about the performance of the model. I just want to know if there is any problem about the super-parameters in my training script. Because it is important for me to reproduce the training process of the model with the best performance.
Thanks for your quick response!

**Comment by stephenroller** [comment] 2019-11-26 22:38
https://github.com/facebookresearch/ParlAI/blob/master/projects/personachat/scripts/kvmemnn_train.sh contains hyperparameters releases by the original author. I haven’t run that script so Please report back how close it brings you.

**Comment by stephenroller** [comment] 2019-11-26 22:39
Ah that’s what you had. Note the difference in num threads, which means that this script is equivalent to much longer train/valid times.

**Comment by wtma** [comment] 2019-11-28 14:28
Hi，it seems that the reason is not the num threads. I have trained the model again by the script kvmemnn_train.sh and the performance is only a litter higher than before:
For the task 'No Persona', the hits@1 in validation: 31.6, test: 32.2, which is still obvious worse than the paper 34.9.
For the task 'Original Persona', the hits@1 in validation is around 48.0 .

**Comment by stephenroller** [comment] 2019-11-29 05:59
Try setting validation patience to 40 and just running a long time. I suspect your machine is just not as big so hogwild isn’t as effective.

**Comment by stephenroller** [comment] 2019-12-12 16:10
Closing due to inactivity. Feel free to reopen.

**Closed by stephenroller** 2019-12-12 16:10 UTC
