### ISSUE TITLE
ImportError: No module named 'parlai.zoo.convai2'

### ISSUE THREAD

**Issue by brendabrandy** [facebookresearch/ParlAI#887] opened 2018-06-19 13:45 UTC
When trying to run `~/ParlAI/projects/convai2/baselines/seq2seq/interactive.py`, the following error occurs:
```
Traceback (most recent call last):
  File "/home/sogun3/ParlAI/parlai/core/build_data.py", line 234, in modelzoo_path
    my_module = importlib.import_module(module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'parlai.zoo.convai2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "interactive.py", line 22, in <module>
    opt = parser.parse_args()
  File "/home/sogun3/ParlAI/parlai/core/params.py", line 395, in parse_args
    self.opt['model_file'])
  File "/home/sogun3/ParlAI/parlai/core/build_data.py", line 237, in modelzoo_path
    except (ModuleNotFoundError, AttributeError):
NameError: name 'ModuleNotFoundError' is not defined
```
Did anyone have a similar issue?

**Comment by jaseweston** [comment] 2018-06-19 13:53
I cannot reproduce that with the latest sync on the repo.
@alexholdenmiller ?

**Comment by brendabrandy** [comment] 2018-06-19 15:39
@jaseweston does the script ever try to reference `~/parlai/zoo/convai2`? If so, there might be a problem because no such folder exist in the repo.

**Comment by alexholdenmiller** [comment] 2018-06-20 20:05
@brendabrandy are you using python 3.6?

**Comment by alexholdenmiller** [comment] 2018-06-20 20:13
I'm guessing you aren't, I didn't realize ModuleNotFoundError is 3.6 only. I'm replacing all of them with ImportError in #897, which should fix your issue (or you can upgrade to 3.6 in the meantime).

**Comment by alexholdenmiller** [comment] 2018-06-20 21:11
diff merged, I'll close this for now but please reopen if you experience again!

**Closed by alexholdenmiller** 2018-06-20 21:11 UTC

**Comment by AnnaSou** [comment] 2020-03-11 19:28
Hello, I am having quite similar error for python 3.7:

Traceback (most recent call last):
  File "transfer-learning-conv-ai/ParlAI/parlai/core/build_data.py", line 422, in modelzoo_path
    my_module = importlib.import_module(module_name)
  File "miniconda3/envs/py37/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai.zoo.convai2.build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transfer-learning-conv-ai/ParlAI/parlai/core/build_data.py", line 429, in modelzoo_path
    my_module = importlib.import_module(module_name_)
  File "miniconda3/envs/py37/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'parlai.zoo.convai2.build'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../convai_evaluation.py", line 239, in <module>
    eval_fct(opt)
  File "transfer-learning-conv-ai/ParlAI/projects/convai2/eval_hits.py", line 29, in eval_hits
    report = eval_model(opt, print_parser)
  File "transfer-learning-conv-ai/ParlAI/parlai/scripts/eval_model.py", line 159, in eval_model
    agent = create_agent(opt, requireModelExists=True)
  File "transfer-learning-conv-ai/ParlAI/parlai/core/agents.py", line 399, in create_agent
    model = model_class(opt)
  File "transfer-learning-conv-ai/convai_evaluation.py", line 73, in __init__
    convai_dict = build_dict()
  File "transfer-learning-conv-ai/ParlAI/projects/convai2/build_dict.py", line 35, in build_dict
    opt = parser.parse_args(args="")
  File "transfer-learning-conv-ai/ParlAI/parlai/core/params.py", line 987, in parse_args
    self._process_args_to_opts(args)
  File "transfer-learning-conv-ai/ParlAI/parlai/core/params.py", line 954, in _process_args_to_opts
    self.opt.get('datapath'), self.opt[each_key]
  File "transfer-learning-conv-ai/ParlAI/parlai/core/build_data.py", line 434, in modelzoo_path
    f'Could not find pretrained model in {module_name} or {module_name_}.'
ImportError: Could not find pretrained model in parlai.zoo.convai2.build or parlai.zoo.convai2.build.


Thanks

**Comment by stephenroller** [comment] 2020-03-12 04:14
Hi @AnnaSou. Rewind to this older commit, which is before that broke. I’ve decided we won’t support the convai2 models in master any longer. https://github.com/facebookresearch/ParlAI/releases/tag/convai2archive

**Comment by AnnaSou** [comment] 2020-03-12 14:55
Hello Stephen,
Thanks for the reply! it is nice to get one from somebody whose papers you are reading now.
Best,
Anna

**Comment by stephenroller** [comment] 2020-03-12 19:22
@AnnaSou Don't hesitate if you have more questions, we're happy to have the users. Next time open a new issue please.
