### ISSUE TITLE
Can't allocate memory when training transformer ranker on Ubuntu dataset

### ISSUE THREAD

**Issue by coderkhaleesi** [facebookresearch/ParlAI#2240] opened 2019-12-04 01:20 UTC
The first problem is the candidate encoding is taking almost 8-10 hours. I am using a 16GB machine with 2 CPUs.

The second issue is that I am running out of memory while training.
I want to know how much memory should I start with and how much time the encoding should take?

These are the logs:

[setting fixed_candidates path to: /tmp/tr_ubuntu.cands-ubuntu.cands ]
[ Loading fixed candidate set from /tmp/tr_ubuntu.cands-ubuntu.cands ]
[ Vectorizing fixed candidate set (1665 batch(es) of up to 512) ]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 1665/1665 [01:02<00:00, 26.63it/s]
[ Saving fixed candidate set vectors to /tmp/tr_ubuntu.tr_ubuntu.cands-ubuntu.vecs ]
[ Encoding fixed candidates set from (3329 batch(es) of up to 256) ]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 3329/3329 [12:37:03<00:00, 13.64s/it]
[ Saving fixed candidate set encodings to /tmp/tr_ubuntu.tr_ubuntu.cands-ubuntu.encs ]
[ Loaded fixed candidate set (n = 564104) from vocabulary ]
[ Encoding fixed candidates set from (2204 batch(es) of up to 256) ]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 2204/2204 [00:40<00:00, 54.07it/s]
[creating task(s): ubuntu]
loading: /home/ubuntu/ParlAI/data/Ubuntu/train.csv
[ training... ]
/home/ubuntu/ParlAI/parlai/core/torch_ranker_agent.py:694: UserWarning: [ Executing train mode with a common set of fixed candidates (n = 852212). ]
  "(n = {}). ]".format(mode, len(self.fixed_candidates))
Traceback (most recent call last):
  File "examples/train_model.py", line 17, in <module>
    TrainLoop(opt).train()
  File "/home/ubuntu/ParlAI/parlai/scripts/train_model.py", line 715, in train
    world.parley()
  File "/home/ubuntu/ParlAI/parlai/core/worlds.py", line 329, in parley
    acts[1] = agents[1].act()
  File "/home/ubuntu/ParlAI/parlai/core/torch_agent.py", line 1760, in act
    return self.batch_act([self.observation])[0]
  File "/home/ubuntu/ParlAI/parlai/core/torch_agent.py", line 1787, in batch_act
    output = self.train_step(batch)
  File "/home/ubuntu/ParlAI/parlai/core/torch_ranker_agent.py", line 396, in train_step
    raise e
  File "/home/ubuntu/ParlAI/parlai/core/torch_ranker_agent.py", line 382, in train_step
    scores = self.score_candidates(batch, cand_vecs)
  File "/home/ubuntu/ParlAI/parlai/agents/transformer/transformer.py", line 280, in score_candidates
    context_h, cands_h = self.model(xs=batch.text_vec, mems=mems, cands=cand_vecs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/ParlAI/parlai/agents/transformer/modules.py", line 274, in forward
    cands_h = self.encode_cand(cands)
  File "/home/ubuntu/ParlAI/parlai/agents/transformer/modules.py", line 227, in encode_cand
    encoded = self.cand_encoder(words)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/ParlAI/parlai/agents/transformer/modules.py", line 322, in forward
    return self.mlp(self.transformer(*args))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/ParlAI/parlai/agents/transformer/modules.py", line 493, in forward
    positions = (mask.cumsum(dim=1, dtype=torch.int64) - 1).clamp_(min=0)
**RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 4274695392 bytes. Error code 12 (Cannot allocate memory)**

Any help would be appreciated.

**Comment by stephenroller** [comment] 2019-12-10 22:05
Marking as a duplicate of #2250 where we've been chatting already.

**Closed by stephenroller** 2019-12-10 22:05 UTC
