### ISSUE TITLE
Error while deserializing preprocessed data

### ISSUE THREAD

**Issue by yyy0506** [facebookresearch/ParlAI#1539] opened 2019-03-09 15:30 UTC
Hello, I am Yeonchan Ahn from Seoul National University.
Thank you for your efforts. It really helps my research.

While using your framework, I found that loading some of the elements of JSON dict object are being skipped while deserializing data. (i.e. in the `deserialize` function in _core/pytorch_data_teacher.py_ ), which causes the following error.

> Traceback (most recent call last):
>   File "/home/aaa/codes/ParlAI/projects/kgd/copy_s2s/mm/train_kcats2s.py", line 76, in <module>
>     TrainLoop(opt).train()
>   File "/home/aaa/codes/ParlAI/parlai/scripts/train_model.py", line 505, in train
>     world.parley()
>   File "/home/aaa/codes/ParlAI/parlai/core/worlds.py", line 666, in parley
>     batch_act = self.batch_act(agent_idx, batch_observations[agent_idx])
>   File "/home/aaa/codes/ParlAI/parlai/core/worlds.py", line 639, in batch_act
>     batch_actions = a.batch_act(batch_observation)
>   File "/home/aaa/codes/ParlAI/parlai/core/torch_agent.py", line 1316, in batch_act
>     batch = self.batchify(observations)
>   File "/home/aaa/codes/ParlAI/projects/kgd/copy_s2s/copy_s2s.py", line 344, in batchify
>     return super().batchify(*args, **kwargs)
>   File "/home/aaa/codes/ParlAI/parlai/core/torch_agent.py", line 1076, in batchify
>     y_lens = [y.shape[0] for y in label_vecs]
>   File "/home/aaa/codes/ParlAI/parlai/core/torch_agent.py", line 1076, in <listcomp>
>     y_lens = [y.shape[0] for y in label_vecs]
> AttributeError: 'dict' object has no attribute 'shape'

When I comment out the line which is `del obj[key]`, the error's disappeared and it seems to work fine. 
What does this line do for?

**Comment by stephenroller** [comment] 2019-03-09 17:23
Hi Yeonchan,

Thanks for reaching out. Do you happen to know why they're failing to be deserialized? Can you post a command to reproduce it? I'm a heavy user of pytorch_data_teacher and I haven't seen this.

I would suggest deleting the pytorch_data_teacher preprocessed files and rerunning `parlai.scripts.build_pytorch_data`. Maybe there was an I/O error somewhere.

**Comment by yyy0506** [comment] 2019-03-10 06:55
Thank you for your quick reply.

Here is the [code reproducing the error](https://gist.github.com/yyy0506/7190e7a8a4d4f67e3fa3b7e83907de5d) and command that I used.
> _python examples/train_model.py -m projects.persona_ext.s2s:NewSeq2seqAgent --pytorch-teacher-task personachat  --pytorch-preprocess True_

When I comment out line number 38, you can see the error disappears.

**Comment by klshuster** [comment] 2019-03-11 14:16
Hi Yeonchan, 

I ran your code (with line 38 uncommented) and I cannot reproduce your error. Can you try merging your code with the latest master branch, deleting the files in `ParlAI/data/personachat_pyt_data/train_NewSeq2seqAgent_preprocess` (and similarly `valid` and `test`), and then try running the command again to see if you get the same error?

**Comment by yyy0506** [comment] 2019-03-16 04:11
Today I confirmed the error occurred again.
In order to remove my machine dependency, I experiment with two different ubuntu 16.04 machine. 
Unfortunately, the error comes out in the both of them.
The procedure is like this.

1) cloned the latest version of Parlai (_c6618f088d9aac471c6d7e92012b758c89417220_).
2) installed new conda env which include pytorch 1.0 and python=3.6 and **parlai** using python setup.py development command
3) made new folder _projects/personachat_ext/s2s/_
4) added the [code reproducing the error](https://gist.github.com/yyy0506/7190e7a8a4d4f67e3fa3b7e83907de5d) under the name of s2s.py
5) ran the command 
_python examples/train_model.py -m projects.personachat_ext.s2s.s2s:NewSeq2seqAgent --pytorch-preprocess True --pytorch-teacher-task personachat:self_original -mf /tmp/Test_

Then you can see the above error.
I'll tell you again for confirmation, you should not fix anything the code in step 4) of the procedure.

**Comment by klshuster** [comment] 2019-03-18 20:46
Hi Yeonchan, I was in fact able to reproduce your error after recloning ParlAI. I have a PR coming very shortly that should solve this issue.

**Comment by stephenroller** [comment] 2019-03-19 03:26
Fixed in #1563

**Closed by stephenroller** 2019-03-19 03:26 UTC
