### ISSUE TITLE
Memory error Amazon Turk Task

### ISSUE THREAD

**Issue by namanahuja** [facebookresearch/ParlAI#1678] opened 2019-04-28 22:24 UTC
I generally get Cannot allocate memory Error in wizard of wikipedia task. 
http://parl.ai.s3-website.us-east-2.amazonaws.com/docs/tutorial_mturk.html#preventing-and-handling-crashes mentions:
If you’re using a model on your local machine, try to share the model parameters whenever possible. Needing new parameters for each of your conversations might run your machine out of memory, causing the data collection to crash in a manner that ParlAI can’t handle

I am not sure what is meant by "try to share the model parameters whenever possible". 
Any help will be great

**Comment by stephenroller** [comment] 2019-04-29 04:19
That recommendation is that you have any models you’re using use share() to provide pointers to models and data, etc. Try not to load anything large into memory on calls to `__init__` of your model.

We work with powerful machines in our day to day work, which might allow us to overlook some inefficiencies. However it also means that we can regularly do things that simply require very high amounts of RAM.

Closing this as a duplicate of #1665. If that’s a mistake, please feel free to reopen and post more detailed information.

**Closed by stephenroller** 2019-04-29 04:19 UTC
